<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [

            /*Combos */
            array( 
                'nombre' =>  "Max Paisa Siderense",
                'precio' => 27000,
                'imagen' => "Paisa_Siderense",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Costillas Baby",
                'precio' => 29000,
                'imagen' => "Costillas_Baby_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Mazorcada",
                'precio' => 29000,
                'imagen' => "Mazorcada_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Chicharron",
                'precio' => 28000,
                'imagen' => "Chicharron",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Chicken Pig",
                'precio' => 28000,
                'imagen' => "Chicken_Pig",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Tocineta",
                'precio' => 28500,
                'imagen' => "Tocineta_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Trifasica",
                'precio' => 19000,
                'imagen' => "Trifasica",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Pollo Agridulce",
                'precio' => 19500,
                'imagen' => "Pollo_Agridulce",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Cerdo a la Naranja",
                'precio' => 18500,
                'imagen' => "Cerdo_Naranja",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Mazorcada",
                'precio' => 19000,
                'imagen' => "Mazorcada",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Costillas Baby",
                'precio' => 19500,
                'imagen' => "Costillas_Baby_1",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Tocineta",
                'precio' => 19000,
                'imagen' => "Tocineta",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Bombon de Pollo",
                'precio' => 14500,
                'imagen' => "Bombon_Pollo",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Longui",
                'precio' => 13500,
                'imagen' => "Longui",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Salchi",
                'precio' => 8500,
                'imagen' => "Salchi",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Kids Ranchero",
                'precio' => 13000,
                'imagen' => "Kids",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Chicken BBQ",
                'precio' => 17000,
                'imagen' => "Chicken_BQQ",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Búfalo Wings",
                'precio' => 22000,
                'imagen' => "Bufalo_Wings",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Chorizo",
                'precio' => 14500,
                'imagen' => "Chorizo",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Maicitos",
                'precio' => 17500,
                'imagen' => "Maicitos",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Boom Granjero",
                'precio' => 79000,
                'imagen' => "Boom_Granjero",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Crispy Chicken",
                'precio' => 32000,
                'imagen' => "Crispy_Chicken",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Max Papas Chips",
                'precio' => 3500,
                'imagen' => "Chips",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Papa Criolla",
                'precio' => 4500,
                'imagen' => "Criollas",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            /* Adiciones */
            array( 
                'nombre' =>  "Tocineta",
                'precio' => 6000,
                'imagen' => "Adicion_Tocineta",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Chicharron",
                'precio' => 7500,
                'imagen' => "Adicion_Chicharron",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Salchicha Ranchera",
                'precio' => 5000,
                'imagen' => "Adicion_Salchicha_Ranchera",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Chorizo Parrillero",
                'precio' => 5000,
                'imagen' => "Adicion_Chorizo_Parrillero",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Costillas Baby",
                'precio' => 7500,
                'imagen' => "Adicion_Costillas_Baby",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Longaniza",
                'precio' => 4500,
                'imagen' => "Adicion_Longaniza",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Bombon de Pollo",
                'precio' => 6000,
                'imagen' => "Adicion_Bombon",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Salchicha Tradicional",
                'precio' => 4000,
                'imagen' => "Adicion_Salchicha_Tradicional",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Huevos Codorniz X3",
                'precio' => 2000,
                'imagen' => "Adicion_Huevos_Codorniz_X3",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Carne Desmechada",
                'precio' => 6500,
                'imagen' => "Adicion_Carne_Desmechada",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pollo Desmechado",
                'precio' => 6500,
                'imagen' => "Adicion_Pollo_Desmechado",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Croqueta Agridulce",
                'precio' => 6500,
                'imagen' => "Adicion_Croqueta_Agridulce",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Croquetas Naranja",
                'precio' => 6500,
                'imagen' => "Adicion_Croquetas_Naranja",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Papa Artesanal",
                'precio' => 6500,
                'imagen' => "Adicion_Papa_Artesanal",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Papa Criolla",
                'precio' => 4500,
                'imagen' => "Adicion_Papa_Criolla",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Maduritos",
                'precio' => 2500,
                'imagen' => "Adicion_Maduritos",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pico de Gallo",
                'precio' => 2500,
                'imagen' => "Adicion_Pico_de_Gallo",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Guacamole",
                'precio' => 2500,
                'imagen' => "Adicion_Guacamole",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Mazorca",
                'precio' => 2500,
                'imagen' => "Adicion_Mazorca",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Arepa con Queso",
                'precio' => 2000,
                'imagen' => "Adicion_Arepa_con_Queso",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Queso Costeño",
                'precio' => 5000,
                'imagen' => "Adicion_Queso_Costeño",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Alitas X1",
                'precio' => 2500,
                'imagen' => "Adicion_Alitas_X1",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Maicitos",
                'precio' => 2500,
                'imagen' => "Adicion_Maicitos",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            /* Salsas Productos */

            array( 
                'nombre' =>  "Rosada",
                'precio' => 1500,
                'imagen' => "Salsa_Rosada",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tartara",
                'precio' => 1500,
                'imagen' => "Salsa_Tartara",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ceviche",
                'precio' => 1500,
                'imagen' => "Salsa_Ceviche",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ajo",
                'precio' => 1500,
                'imagen' => "Salsa_Ajo",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Maiz",
                'precio' => 1500,
                'imagen' => "Salsa_Maiz",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "BQQ",
                'precio' => 1500,
                'imagen' => "Salsa_BQQ",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Roja",
                'precio' => 1500,
                'imagen' => "Salsa_Roja",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Piña",
                'precio' => 1500,
                'imagen' => "Salsa_Piña",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            /*Bebidas */

            array( 
                'nombre' =>  "Coca Cola",
                'precio' => 4500,
                'imagen' => "Bebidas_Coca_Cola",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Manzana",
                'precio' => 4500,
                'imagen' => "Bebidas_Manzana",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),


        ];

        DB::table('productos')->insert($datos);
    }
}
